export const site = {
  name: "Usta Sigortacı",
  legalName: "Usta Sigorta Aracılık Hizmetleri",
  logo: "/brand/logo-stacked-navy.png",
  tagline: "Türkiye'nin usta işi sigorta platformu",
  description:
    "Kasko, trafik, DASK, sağlık ve 14 farklı sigorta türünde 25'ten fazla sigorta şirketinden saniyeler içinde teklif karşılaştırın, en uygun poliçeyi online satın alın.",
  url: "https://ustasigortaci.com",
  phone: "0505 396 05 86",
  phoneHref: "tel:+905053960586",
  whatsapp: "+90 505 396 05 86",
  whatsappHref: "https://wa.me/905053960586",
  email: "gamze@ustasigortaci.com",
  address: "Barbaros Mah. Al Zambak Sk. Varyap Meridian 2 A Blok, Daire 47, Kat 4, Ataşehir / İstanbul",
  addressParts: {
    street: "Barbaros Mah. Al Zambak Sk. Varyap Meridian 2 A Blok D:47 K:4",
    district: "Ataşehir",
    city: "İstanbul",
    postalCode: "34746",
    country: "TR",
  },
  geo: { lat: 40.9995776, lng: 29.1002751 },
  mapsEmbedUrl: "https://www.google.com/maps?q=40.9995776,29.1002751&hl=tr&z=16&output=embed",
  mapsDirectionsUrl: "https://www.google.com/maps/dir/?api=1&destination=40.9995776,29.1002751",
  founder: {
    name: "Gamze Usta",
    title: "Kurucu Ortak",
    phone: "0505 396 05 86",
    phoneHref: "tel:+905053960586",
    email: "gamze@ustasigortaci.com",
  },
  workingHours: "Hafta içi 08:30 – 20:00, Cumartesi 09:00 – 18:00",
  social: {
    twitter: "https://twitter.com/ustasigortaci",
    instagram: "https://instagram.com/ustasigortaci",
    linkedin: "https://linkedin.com/company/ustasigortaci",
    youtube: "https://youtube.com/@ustasigortaci",
  },
  stats: {
    customers: "1,2 milyon+",
    partners: "25+",
    products: "14",
    experience: "12",
  },
} as const;
